server:
  port: 8080
  error:
    include-message: always     # show reason in error response body

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  application:
    name: DEMO
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    url: jdbc:mariadb://localhost:3306/book
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

api:
  base:
    path: /api

logging:
  pattern:
    console: "%d [%t] [${PID}] [%p] %logger : %msg %ex%n"   # t: thread, p: level
    file: "%d [%t] [${PID}] [%p] %logger : %msg %ex%n"
  file:
    path: "/User/logs/"
    name: "/User/logs/demo.log"
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30
      total-size-cap: 1GB
  level:
    root: info
    org:
      springframework: warn
      apache: warn